site_name: KB Ciao! - Manuale Operativo
site_description: Base di conoscenza del sistema di cassa Ciao! e applicativi correlati
theme:
  name: material
  language: it
  logo: assets/dxc.png
  favicon: assets/dxc.png
  palette:
    primary: custom
    accent: custom
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - "Sistema di cassa e applicativi correlati": 01-sistema-di-cassa-e-applicativi-correlati/index.md
  - "Operazioni di apertura e di chiusura": 02-operazioni-di-apertura-e-di-chiusura/index.md
  - "Gestione anagrafica cliente": 03-gestione-anagrafica-cliente/index.md
  - "Gestione dati prescrizione e visite": 04-gestione-dati-prescrizione-e-visite/index.md
  - "Creazione WO Frame + Lenti o Solo Lenti": 05-creazione-wo-frame-lenti-o-solo-lenti/index.md
  - "Tracciatura": 06-tracciatura/index.md
  - "Ricezione ordine Complete Job -- FTC -- Lens Only e consegna al cliente": 07-ricezione-ordine-complete-job-ftc-lens-only-e-consegna-al-cl/index.md
  - "Vendita occhiali da sole": 08-vendita-occhiali-da-sole/index.md
  - "Vendita lenti a contatto": 09-vendita-lenti-a-contatto/index.md
  - "Vendita accessori, ricambi e servizi": 10-vendita-accessori-ricambi-e-servizi/index.md
  - "One hour Lenses": 11-one-hour-lenses/index.md
  - "Vendita da Smart Shopper": 12-vendita-da-smart-shopper/index.md
  - "Gestione promozioni": 13-gestione-promozioni/index.md
  - "14 Gestione servizi post-vendita": 14-14-gestione-servizi-post-vendita/index.md
  - "15 Reporting": 15-15-reporting/index.md
  - "16 Elenco Ordini: Attivo, Archivio e Caparra": 16-16-elenco-ordini-attivo-archivio-e-caparra/index.md
  - "17 Operative": 17-17-operative/index.md
  - "18 Tag printing": 18-18-tag-printing/index.md
